### ISSUE TITLE
yarn install throws build error on blake2js

### ISSUE THREAD

**Issue by arikan** [shawntabrizi/substrate-package#7]
```
yarn install v1.16.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @polkadot/wasm-crypto@0.3.1" has unmet peer dependency "@polkadot/util@*".
[4/4] 🔨  Building fresh packages...
[-/4] ⠐ waiting...
[2/4] ⠐ blake2js
[-/4] ⠐ waiting...
error /Users/arikan/Sites/substrate-artistcollections/artistcollections-ui/node_modules/blake2js: Command failed.
Exit code: 1
...
25 warnings and 1 error generated.
make: *** [Release/obj.target/addon/src/blake2.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/12.1.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 17.2.0
gyp ERR! command "/usr/local/Cellar/node/12.1.0/bin/node" "/usr/local/Cellar/node/12.1.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/arikan/Sites/substrate-artistcollections/artistcollections-ui/node_modules/blake2js
gyp ERR! node -v v12.1.0
```

**Comment by arikan** [comment]
Current solution: change the node version to 10.16.0 instead of the latest one.

**Comment by ltfschoen** [comment]
Solution for all users may be to create a PR to update the package.json of substrate-ui that specifies the supported version of Node.js and Yarn.
